services:
  upper_eat_back:
    build:
      context: ./uppereat_back
    ports:
      - "4000:4000" 
    environment:
      - DATABASE_URL=postgresql://lucianoojeda:Cosmefulanito12@db:5432/restaurant_db
      - PORT=4000
    volumes:
      - ./uppereat_back:/app
    depends_on:
      - db

  upper_eat_front:
    build:
      context: ./uppereat_front
    ports:
      - "3000:3000"
    volumes:
      - ./uppereat_front:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=lucianoojeda
      - POSTGRES_PASSWORD=Cosmefulanito12
      - POSTGRES_DB=restaurant_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
